### ISSUE TITLE
dry-configurable >= 0.14 and dry-initializer >= 3.1 requires ruby >= 2.7

### ISSUE THREAD

**Issue by nijikon** [karafka/sidekiq-backend#119]
If we will update `dry-configurable` to a version higher or equal `0.14` and `dry-initializer` to a version higher or equal `3.1` CI will fail because we still support ruby 2.6 and those versions do not longer support it.

**Comment by nijikon** [comment]
@mensfeld I'm 👍 in dropping 2.6. Do we want to drop the support completely? Do you want karafka 2.0 to support 2.6 or not?

**Comment by mensfeld** [comment]
@nijikon I think it can but we should not give any warranties on that.

**Comment by nijikon** [comment]
@mensfeld sounds good, will drop 2.6 support on all the repositories.

**Comment by mensfeld** [comment]
@nijikon is it done?

**Comment by nijikon** [comment]
We officially dropped support for ruby 2.6, refs https://github.com/karafka/sidekiq-backend/pull/120
