### ISSUE TITLE
ApplicationWorker do not serialize to JSON safely

### ISSUE THREAD

**Issue by CR4567** [karafka/sidekiq-backend#122]
With Sidekiq 6.4.1, they added a deprecation warning 
"Job arguments to ApplicationWorker do not serialize to JSON safely. This will raise an error in Sidekiq 7.0."
Is there a plan to get rid of that?
I know that there are no plans for further use after Karafka 2.0 but would be nice to have a solution also for users of versions below 2.0

**Comment by CR4567** [comment]
awesome. Thanks for the quick reply.
Looking really into version 2.0 but I assume we will have a longer test phase until updating production ;-)

**Comment by mensfeld** [comment]
Go with 2.0. Companies already use alpha1 in production, I am going to release alpha2 this week with small improvements. The only thing missing to consider it stable is docs. Aside from that you will always get help on our slack.

Anyhow, whatever you choose, I am not going anywhere ;)

**Comment by mensfeld** [comment]
@CR4567 I do not see this error when playing with example app 1.4 and sidekiq backend: https://github.com/karafka/example-apps/tree/master/v1.4-non-rails

Can you create a repro for me? It may be related to your data and the way you serialize it rather than Karafka but happy too look into it more if I get a repro. Thanks :pray:

**Comment by mensfeld** [comment]
NVMD, got it!

**Comment by mensfeld** [comment]
@CR4567 I did not forget. I have the fix. Just need to update the specs. You can expect release in the upcoming week.

**Comment by CR4567** [comment]
thanks a lot for fixing it that quickly.

**Comment by mensfeld** [comment]
@CR4567 would you mind giving this a spin? https://github.com/karafka/sidekiq-backend/pull/123

**Comment by CR4567** [comment]
just updated but the warning is still there.

**Comment by mensfeld** [comment]
@CR4567 do you use any custom interchangers? I was able to do this to the example v1.4:

ref: https://github.com/karafka/example-apps/tree/master/v1.4-non-rails

```ruby
# frozen_string_literal: true

source 'https://rubygems.org'

plugin 'diffend'

# ActiveSupport and rexml are only used for XML support
gem 'activesupport'
gem 'rexml'

gem 'karafka', '~> 1.4'
gem 'karafka-sidekiq-backend', github: 'karafka/sidekiq-backend', branch: '#122'

group :development, :test do
  gem 'byebug', platform: :ruby
  gem 'karafka-testing', '~> 1.4'
  gem 'rspec'
  gem 'simplecov'
end
```

and it works without any warnings when running both server and worker.

**Comment by mensfeld** [comment]
pretty much no warnings when scheduling the jobs:

```
I, [2022-02-23T16:59:37.719539 #3327574]  INFO -- : 1 messages on pong topic delegated to Pong::PongConsumer
I, [2022-02-23T16:59:38.746619 #3327574]  INFO -- : Scheduling of 1 messages to Sidekiq on topic ping took 1 ms
I, [2022-02-23T16:59:38.746688 #3327574]  INFO -- : 1 messages on ping topic delegated to Pong::PingConsumer
I, [2022-02-23T16:59:39.774344 #3327574]  INFO -- : Scheduling of 1 messages to Sidekiq on topic pong took 1 ms
I, [2022-02-23T16:59:39.774438 #3327574]  INFO -- : 1 messages on pong topic delegated to Pong::PongConsumer
```

**Comment by CR4567** [comment]
I tried the example app and the warnings disappear.
But for my rails app it doesn't work. 
I compared the gem versions but can't see a difference.
  * sidekiq (6.4.1)
  * karafka (1.4.13)
  * karafka-sidekiq-backend (1.4.4 ba927e0)

I will try to investigate further.

**Comment by mensfeld** [comment]
@CR4567 if you deserialize data in karafka prior to it being enqueued or you use custom deserializer or anything non-standard, it may be, that it is your data that is triggering this error.

**Comment by CR4567** [comment]
that was my thoughts also, but I disabled everything I found but still the same behavior. I also tried to send the same example data, without any change. 
I will try a plain rails example by next week. Maybe it helps in finding the differences.

**Comment by mensfeld** [comment]
@CR4567 please keep me posted :pray: I will wait for you with the release. Maybe I missed something, though I cannot find anything

**Comment by CR4567** [comment]
sry I had to fully check all my plugins and configs. But finally I found the stupid one... 
I'm using the 'oj' gem to to optimize Json parsing and it seems relate to this gem. After I disabled it the warning also disappears. 
But I didn't found the real issue here.

But for you it means your fix is definitely working ;-)

**Comment by mensfeld** [comment]
Great. I will craft a release tomorrow.

**Comment by mensfeld** [comment]
Merged and crafting a releease so will close this one.
