### ISSUE TITLE
Consumer class names must have the word "Consumer" in it in order to work

### ISSUE THREAD

**Issue by elioncho** [karafka/sidekiq-backend#29]
**BUG REPORT**

Hi,

I found a bug when my application tries to consume a task using Sidekiq. I created an example here: https://github.com/elioncho/karafka_rails_example

The problem happens when the consumer classes do not have the word "Consumer" on their names. I have 4 consumers on my application

```
App.consumer_groups.draw do
  topic :consumer_is_here do
    consumer ConsumerIsHere
  end
  topic :no_magic_word do
    consumer NoMagicWord
  end
  topic :with_magic_word_consumer do
    consumer WithMagicWordConsumer
  end
  topic :without_the_magic_word do
    consumer WithoutTheMagicWord
  end
end
```

The 2 of them that include the word "Consumer" (**ConsumerIsHere** and **WithMagicWordConsumer**) work fine, they are executed by Sidekiq. The 2 others are not.

You can test this by doing the following:

First, launch the application
```
docker-compose up -d
``` 

Once all the services are running, run:
```
docker-compose exec app rails c
```

Try the following commands inside the console:
```
WaterDrop::AsyncProducer.call('{"message":"consumer_is_here"}',topic: "consumer_is_here")
WaterDrop::AsyncProducer.call('{"message":"no_magic_word"}',topic: "no_magic_word")
WaterDrop::AsyncProducer.call('{"message":"with_magic_word_consumer"}',topic: "with_magic_word_consumer")
WaterDrop::AsyncProducer.call('{"message":"without_the_magic_word"}',topic: "without_the_magic_word")
```

Open a new tab in your terminal and run:
```
docker-compose logs -f worker
```

You'll be able to see that Sidekiq only consumes the tasks whose name includes the word "Consumer".

**Comment by mensfeld** [comment]
Btw @elioncho the link you've provided does not work.

**Comment by mensfeld** [comment]
When I think about it now I think this name matching is :hankey: 

It creates a pairs of consumer -> worker based on the name and replaces the `Consumer` part with the `Worker` part while I think it should actually build at a worker as a postfix, so it would be `ExampleConsumer` and `ExampleConsumerWorker`. That way it not only directly references the consumer class name but also allows for way better mapping when there is no `Consumer` involved in the naming. WDYT @elioncho?

Also as a temp fix, you can just define your own worker class:

```ruby
App.consumer_groups.draw do
  topic :consumer_is_here do
    consumer ConsumerIsHere
    worker AnyWorkerYouCreated
  end
  topic :no_magic_word do
    consumer NoMagicWord
    worker AnyWorkerYouCreated
  end
  topic :with_magic_word_consumer do
    consumer WithMagicWordConsumer
  end
  topic :without_the_magic_word do
    consumer WithoutTheMagicWord
  end
end
```

**Comment by mensfeld** [comment]
Hey @elioncho would you mind giving it a spin: https://github.com/karafka/karafka/pull/494 - keep in mind that it is for `1.3` so if you use `1.2` just backport this one injection line ;)

**Comment by elioncho** [comment]
> When I think about it now I think this name matching is 💩
> 
> It creates a pairs of consumer -> worker based on the name and replaces the `Consumer` part with the `Worker` part while I think it should actually build at a worker as a postfix, so it would be `ExampleConsumer` and `ExampleConsumerWorker`. That way it not only directly references the consumer class name but also allows for way better mapping when there is no `Consumer` involved in the naming. WDYT @elioncho?
> 
> 

Makes sense to me

> Hey @elioncho would you mind giving it a spin: [karafka/karafka#494](https://github.com/karafka/karafka/pull/494) - keep in mind that it is for `1.3` so if you use `1.2` just backport this one injection line ;)

This solves the issue ;) 👍

**Comment by mensfeld** [comment]
@elioncho I'm closing. Will backport to 1.2 and make a release for you.

**Comment by mensfeld** [comment]
@elioncho here you go: https://diff.coditsu.io/gems/karafka/1.2.11/1.2.12
