### ISSUE TITLE
Deprecate for 2.0

### ISSUE THREAD

**Issue by mensfeld** [karafka/sidekiq-backend#40]
This won't be needed with multi-threaded 2.0 version. I don't see a reason to support that beyond `1.3` as `perform_async` isn't that big of a hustle (unless the community has valid arguments to keep it).

**Comment by paneq** [comment]
Moving messages to sidekiq is great if in some use-cases you care more about sidekiq features (automatic retries, processing every message separately) compared to kafka mode of operations.

**Comment by mensfeld** [comment]
@paneq I absolutely agree. We're not planning to disallow using that but we plan to provide a in karafka multi threaded way of running things. There won't be anything blocking you from passing the messages to Sidekiq. Its just that we don't want to support that out of the box as the overhead of a custom implementation is almost non-existing (consumer with `#perform_async`)

**Comment by mensfeld** [comment]
@paneq closing this as I added the deprecation notice. On top of that while writing the upgrade doc for 2.0 I will include a section on how to achieve this functionality in `2.0` and how to migrate it.
