### ISSUE TITLE
Clarify possible interchanger values in the documentation

### ISSUE THREAD

**Issue by paneq** [karafka/sidekiq-backend#57]
The documentation says:

```ruby
or on a per topic level:

App.routes.draw do
  consumer_group :videos_consumer do
    topic :binary_video_details do
      consumer Videos::DetailsConsumer
      worker Workers::DetailsWorker
      interchanger Interchangers::MyCustomInterchanger
    end
  end
end
```

What are the possible interchanger names? What name should I provide to use sidekiq only for some topics and what name to process directly in other topics.

**Comment by mensfeld** [comment]
> What name should I provide to use sidekiq only for some topics

Any name you want. It does not do any "magic" based on the name.

> what name to process directly in other topics.

Don't assign anything or just use the default interchanger: `Karafka::Interchanger`.

If the answer is sufficient please close :)

**Comment by paneq** [comment]
I am probably having a trouble expressing what I am trying to achieve.

Let's say I have two topic and I want to process one of them via sidekiq and one of them directly in karafka. I don't want to set:

```
class App < Karafka::App
  setup do |config|
    config.backend = :sidekiq
  end
end
```

because for each topic I want to decide on the backend explicitly.

How do I configure it on per topic-level 

```
App.routes.draw do
  consumer_group :a do
    topic :a do
      consumer ConsumerA
      # configure to use karafka directly
    end
  end

  consumer_group :b do
    topic :b do
      consumer ConsumerB
      # configure to use sidekiq
    end
  end
end
```

?

I am trying to understand what is the equivalent of `config.backend = :sidekiq` on per topic level, because nothing in the readme in that section uses the word `sidekiq` so I am confused :)

Is it the invocation of the `worker WorkerName` method which triggers sidekiq backend or `interchanger` maybe?

**Comment by paneq** [comment]
This is described here: https://github.com/karafka/karafka/wiki/Consuming-messages#backends

**Comment by mensfeld** [comment]
Sorry for the late reply. I didn't spend too much time in front of a computer during the weekend. Glad you found your answer. Do you think there's anything we could do better in the docs to make it more clear for other people with similar question?

**Comment by paneq** [comment]
@mensfeld just this https://github.com/karafka/sidekiq-backend/pull/58 would help a lot :) It would be also nice to describe if `worker` and `interchanger` are optional or mandatory options.
