### ISSUE TITLE
undefined method `fetch' for #<Karafka::Params::Params>

### ISSUE THREAD

**Issue by Jack12816** [karafka/sidekiq-backend#74]
Hey! First things first: thanks for the great gem and its ecosystem! :) 

Nice the last update we encounter an error while processing Kafka message via the Karafka/Sidekiq backend. Looks like the [Karafka::Params::Params](https://github.com/karafka/karafka/blob/master/lib/karafka/params/params.rb) class does not provide a `fetch` method. The error [is located here](https://github.com/karafka/sidekiq-backend/blob/master/lib/karafka/extensions/params_builder.rb#L14).

Full backtrace:
```
NoMethodError: undefined method `fetch' for #<Karafka::Params::Params:0x00007f8cf8cddb88>
[GEM_ROOT]/gems/karafka-sidekiq-backend-1.4.0/lib/karafka/extensions/params_builder.rb:14 :in `from_hash`
[GEM_ROOT]/gems/karafka-sidekiq-backend-1.4.0/lib/karafka/extensions/params_batch_builder.rb:14 :in `block in from_array`
[GEM_ROOT]/gems/karafka-sidekiq-backend-1.4.0/lib/karafka/extensions/params_batch_builder.rb:13 :in `map`
[GEM_ROOT]/gems/karafka-sidekiq-backend-1.4.0/lib/karafka/extensions/params_batch_builder.rb:13 :in `from_array`
[GEM_ROOT]/gems/karafka-sidekiq-backend-1.4.0/lib/karafka/base_worker.rb:51 :in `consumer`
[GEM_ROOT]/gems/karafka-sidekiq-backend-1.4.0/lib/karafka/base_worker.rb:31 :in `perform`
```

Versions in use:
```
1.4.0  karafka
1.4.0  karafka-sidekiq-backend
1.4.1  karafka-testing
6.1.2  sidekiq
1.3.0  ruby-kafka
```

**Comment by mensfeld** [comment]
Did you make sure to consume all the messages before upgrading as stated in the upgrade notes?

**Comment by Jack12816** [comment]
Thanks for the fast reply! Looks like this was missed. Where do I find these upgrade nodes? Couldn't find it in here, nor in the Karafka changelogs.

**Comment by mensfeld** [comment]
@Jack12816 https://github.com/karafka/karafka/wiki/Articles-and-other-references  => [Karafka (Ruby + Kafka) framework 1.4.0 Release Notes](https://mensfeld.pl/2020/09/karafka-framework-1-4-0-release-notes-ruby-kafka/) - I'll make sure to highlight it better next time. Really sorry :pray:

**Comment by mensfeld** [comment]
I'm closing it for now. Please ping me if you need anything more. I'm here to help :)

**Comment by Jack12816** [comment]
Thank you! That helped me a lot!
