### ISSUE TITLE
Consider using tags/releases 

### ISSUE THREAD

**Issue by barthez** [karafka/sidekiq-backend#78]
Hey,

It would be great if you could use tags (or even releases) so it would be easier to review changes while updating dependency in one's projects. Tools like dependabot usually link to diff based on tags.

WDYT?

**Comment by mensfeld** [comment]
just use diffend: https://my.diffend.io/gems/karafka-sidekiq-backend/1.4.0/1.4.1

**Comment by barthez** [comment]
It is, it is. It looks like GitHub tags diff with extra steps though 😆 . Thank anyway!
